// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	IsCompleted bool        `json:"is_completed"`
}
